name: Build plugin

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Plugin
      run: make build-docker

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plugin-binaries
        path: releases
