name: Release plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Plugin
        run: make build-docker
        env:
          VERSION: ${{ github.ref }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin-binaries
          path: releases

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built plugin binaries
        uses: actions/download-artifact@v3
        with:
          name: plugin-binaries
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ./waypoint-plugin-*.zip
